### ISSUE TITLE
Not able to open link in notification 

### ISSUE THREAD

**Issue by Steph4104** [gctools-outilsgc/gccollab-mobile#192]
When you try to open a link from your notification you are not redirect to the content. 

This error appear in the console

![image](https://user-images.githubusercontent.com/15112568/39052063-ac07d322-4478-11e8-8a7d-474594713ea3.png)

**Comment by markwooff** [comment]
Assuming the links you're referring to are these?

![image](https://user-images.githubusercontent.com/5591488/39068048-f44d1040-44a8-11e8-871b-9651c273ddfa.png)

We'll need to change where these links send the user since the link is just pointing them to the GCcollab.ca website instead of redirecting them to the right page within the app. Could also set these links to open in a new tab/window since the app is trying to open it internally.

**Comment by Steph4104** [comment]
Not only these link but all the link in the site notification. The one in the footer (contact us and notification settings) and all the link in the title or description of the notifications.

![image](https://user-images.githubusercontent.com/15112568/39068821-a035c8aa-44ab-11e8-9b63-366451a7bcd3.png)

**Comment by markwooff** [comment]
Yeah it would be the same case for all of these then. We'll have to add some Javascript to capture the clicks to all of these links in the notifications and send the user to the correct location (or to an external browser).

**Comment by Steph4104** [comment]
Also, we should think about the color of the link. On a phone, it's really hard to see the difference between the link and the regular text.

![image](https://user-images.githubusercontent.com/15112568/39069015-53b45eb4-44ac-11e8-91ae-88beed986c70.png)


(This is what you can see on my Pixel)
